name: CI

on:
  push:
    branches:
      - main # Adjust branch name as necessary
  pull_request:
    branches:
      - main # Adjust branch name as necessary

jobs:
  lint-php:
    name: PHP and WPCS Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Packages
        run: composer install --no-progress

      - name: Run PHP Lint
        run: composer run-script lint:php

      - name: Run WPCS Lint
        run: composer run-script lint:wpcs

  generate-docs:
    name: Generate and Deploy Documentation
    runs-on: ubuntu-latest
    needs: lint-php

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install phpDocumentor
        run: |
          curl -L -o phpDocumentor.phar https://github.com/phpDocumentor/phpDocumentor/releases/latest/download/phpDocumentor.phar

      - name: Generate Documentation
        run: php phpDocumentor.phar -d src -t docs

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages # Ensure this is configured in GitHub Pages settings
